---
title: "midterm"
author: "Prajakta Patil"
date: "March 5, 2019"
output: html_document
---

library(ggplot2)
library(nycflights13)
install.packages("nycflights13")
install.packages("tidyr")
library(dplyr)
library("tidyverse")
#Question1
head(flights)
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
#question 2, 4 & 6
dat = read.csv("income.csv", header = TRUE)
head(dat)
dat %>% summarise(mean(M_weekly,na.rm = TRUE))
dat %>% summarise(mean(M_weekly,trim = 0.1,na.rm = TRUE))
dat %>% summarise(median(M_weekly,na.rm = TRUE))
dat %>% summarise(sd(F_workers,na.rm = TRUE))
dat %>% summarise(IQR(F_workers,na.rm = TRUE))
dat %>% summarise(mad(F_workers,na.rm = TRUE))
dat <- mutate(dat, diff= M_weekly - F_weekly )
dat %>% glimpse()
sd_opt= dat %>% summarise(sd(diff,na.rm = TRUE))
round(sd_opt)
#Question 7 & 8
opt = read.csv("optdigits.tra", header = TRUE)
head(opt)
length(opt)
shape(opt)
library(dplyr)
glimpse(opt)
length(opt)
ncol(opt)
nrow(opt)
#Question 10
library(datasets)
data(iris)
summary(iris)
head(iris)
iris.query('Petal.Length > 6')
iris[iris.iloc[:,2] > 6]
iris[iris[:,2] > 6]
iris[iris['Petal.Length'] > 6]
iris[iris.Petal.Length > 6]
iris.query('Petal.Length' > 6)
iris[iris.iloc[:,2] > 6]
iris[,2]

?df.describe()
iris[iris['Petal.Length'] > 6]