install.packages("tidyr")
install.packages("magrittr")
library(tidyverse)
library(magrittr) 
library(dplyr)
m1 <- who %>% gather(key= "Types", value="Cases", new_sp_m014:newrel_f65,na.rm=TRUE)
head(m1, 30)
newm1 <- m1 %>% dplyr::mutate(Types=stringr::str_replace(Types, "newrel","new_rel"))
tail(newm1, 30)
sepm1 <- newm1 %>% tidyr::separate(Types,c("Col1","Methods","SexAge"),sep="_")
newm1 %>% tidyr::separate(Types, into = c("Col1","Methods","SexAge")) %>% group_by(Methods) %>% count(Methods)
head(newm1,30)
m1[order(m1$Cases, decreasing = TRUE),]  